export const POPULATE_TRIPS = 'POPULATE_TRIPS';
export const ADD_TRIP = 'ADD_TRIP';
export const UPDATE_SELECTED_TRIP = 'UPDATE_SELECTED_TRIP';
export const UPDATE_PARTICIPANT_ID = 'UPDATE_PARTICIPANT_ID';
export const ADD_PARTICIPANT_ASYNC = 'ADD_PARTICIPANT_ASYNC';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
