export const POPULATE_STORE = 'POPULATE_STORE';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';
export const UPDATE_ITEM_NAME = 'UPDATE_ITEM_NAME';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';
