export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const UPDATE_AUTOCOMPLETE_ITEMS = 'UPDATE_AUTOCOMPLETE_ITEMS';
export const UPDATE_AUTOCOMPLETE_VALUE = 'UPDATE_AUTOCOMPLETE_VALUE';
