export const RECEIVE_CHECKLISTS = 'RECEIVE_CHECKLISTS';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';
export const UPDATE_ITEM_NAME = 'UPDATE_ITEM_NAME';
